/* tslint:disable */
/* eslint-disable */
export const convert_filemesh_to_obj: (a: number, b: number) => any;
export const convert_filemesh_version: (a: number, b: number, c: number) => any;
export const convert_obj_to_filemesh: (a: number, b: number, c: number) => any;
export const fix_place: (a: number, b: number, c: number, d: number, e: number, f: number, g: any, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number) => [number, number, number, number];
export const is_binary_rbxl: (a: number, b: number) => number;
export const minecraft_map_to_place: (a: number, b: number, c: number) => [number, number, number, number];
export const start: () => void;
export const init_wasm_thread_pool: (a: number) => any;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_mainJS: (a: number) => any;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const wasm_bindgen_69b9755c9aabf95b___convert__closures_____invoke___wasm_bindgen_69b9755c9aabf95b___JsValue__core_b71b0a6f5a906bae___result__Result_____wasm_bindgen_69b9755c9aabf95b___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_69b9755c9aabf95b___convert__closures_____invoke___js_sys_ce4228677d4bba06___Function_fn_wasm_bindgen_69b9755c9aabf95b___JsValue_____wasm_bindgen_69b9755c9aabf95b___sys__Undefined___js_sys_ce4228677d4bba06___Function_fn_wasm_bindgen_69b9755c9aabf95b___JsValue_____wasm_bindgen_69b9755c9aabf95b___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_69b9755c9aabf95b___convert__closures_____invoke___wasm_bindgen_69b9755c9aabf95b___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_69b9755c9aabf95b___convert__closures_____invoke___js_sys_ce4228677d4bba06___futures__task__wait_async_polyfill__MessageEvent______true_: (a: number, b: number, c: any) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
